# Generated by Django 2.0.5 on 2018-12-02 18:31

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=255)),
                ('author_id', models.CharField(max_length=255)),
                ('author_role', models.CharField(choices=[('instructor', 'Instructor'), ('mentor', 'Mentor'), ('coach', 'Coach')], default='mentor', max_length=255)),
                ('session_num', models.PositiveIntegerField()),
                ('session_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('course_feedback', ckeditor.fields.RichTextField(default='.')),
                ('diary', ckeditor.fields.RichTextField()),
                ('payroll_id', models.CharField(default='.', max_length=255)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='NoteForEach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=2525)),
                ('note', ckeditor.fields.RichTextField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Diary')),
            ],
        ),
    ]
