# Generated by Django 2.0.5 on 2018-12-02 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendances', models.CharField(max_length=258)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=50)),
                ('member_id', models.CharField(max_length=50)),
                ('grades', models.CharField(default='[-1]', max_length=258)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.CharField(max_length=500)),
                ('teacher_id', models.CharField(max_length=50)),
                ('grade_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worm.Grade'),
        ),
    ]
